set(_CATKIN_CURRENT_PACKAGE "ddsr_description")
set(ddsr_description_VERSION "0.0.0")
set(ddsr_description_MAINTAINER "Andreu Corominas Murtra <andreu@beta-robots.com>")
set(ddsr_description_PACKAGE_FORMAT "2")
set(ddsr_description_BUILD_DEPENDS )
set(ddsr_description_BUILD_EXPORT_DEPENDS )
set(ddsr_description_BUILDTOOL_DEPENDS "catkin")
set(ddsr_description_BUILDTOOL_EXPORT_DEPENDS )
set(ddsr_description_EXEC_DEPENDS )
set(ddsr_description_RUN_DEPENDS )
set(ddsr_description_TEST_DEPENDS )
set(ddsr_description_DOC_DEPENDS )
set(ddsr_description_URL_WEBSITE "")
set(ddsr_description_URL_BUGTRACKER "")
set(ddsr_description_URL_REPOSITORY "")
set(ddsr_description_DEPRECATED "")