set(_CATKIN_CURRENT_PACKAGE "ddsr_gazebo")
set(ddsr_gazebo_VERSION "0.0.0")
set(ddsr_gazebo_MAINTAINER "Andreu Corominas Murtra <andreu@beta-robots.com>")
set(ddsr_gazebo_PACKAGE_FORMAT "2")
set(ddsr_gazebo_BUILD_DEPENDS "gazebo_ros" "ddsr_description")
set(ddsr_gazebo_BUILD_EXPORT_DEPENDS "gazebo_ros" "ddsr_description")
set(ddsr_gazebo_BUILDTOOL_DEPENDS "catkin")
set(ddsr_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(ddsr_gazebo_EXEC_DEPENDS "gazebo_ros" "ddsr_description")
set(ddsr_gazebo_RUN_DEPENDS "gazebo_ros" "ddsr_description")
set(ddsr_gazebo_TEST_DEPENDS )
set(ddsr_gazebo_DOC_DEPENDS )
set(ddsr_gazebo_URL_WEBSITE "")
set(ddsr_gazebo_URL_BUGTRACKER "")
set(ddsr_gazebo_URL_REPOSITORY "")
set(ddsr_gazebo_DEPRECATED "")