set(_CATKIN_CURRENT_PACKAGE "ddsr_control")
set(ddsr_control_VERSION "0.0.0")
set(ddsr_control_MAINTAINER "Andreu Corominas Murtra <andreu@beta-robots.com>")
set(ddsr_control_PACKAGE_FORMAT "2")
set(ddsr_control_BUILD_DEPENDS "controller_manager" "ddsr_gazebo" "ddsr_description")
set(ddsr_control_BUILD_EXPORT_DEPENDS "controller_manager" "ddsr_gazebo" "ddsr_description")
set(ddsr_control_BUILDTOOL_DEPENDS "catkin")
set(ddsr_control_BUILDTOOL_EXPORT_DEPENDS )
set(ddsr_control_EXEC_DEPENDS "controller_manager" "ddsr_gazebo" "ddsr_description")
set(ddsr_control_RUN_DEPENDS "controller_manager" "ddsr_gazebo" "ddsr_description")
set(ddsr_control_TEST_DEPENDS )
set(ddsr_control_DOC_DEPENDS )
set(ddsr_control_URL_WEBSITE "")
set(ddsr_control_URL_BUGTRACKER "")
set(ddsr_control_URL_REPOSITORY "")
set(ddsr_control_DEPRECATED "")